version: '3.5'

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: ccgtown
      POSTGRES_USER: ccgtown
      POSTGRES_PASSWORD: ccgtown
      PGDATA: /data/postgres
    volumes:
      - .data/postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - nethost
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:4.28
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - .data/pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    links:
      - 'postgres:pgsql-server'
    restart: unless-stopped

networks:
  nethost: