# Generated by Django 3.1.3 on 2020-12-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotators', '0001_squashed_0004_auto_20201125_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
