# Generated by Django 3.1.3 on 2020-11-25 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('annotators', '0002_auto_20201110_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rules',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('words', models.JSONField()),
                ('categories', models.JSONField()),
                ('derivations', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotators.project')),
            ],
            options={
                'db_table': 'sentences',
            },
        ),
    ]
